### PR TITLE
Update

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
- Correct exception printing
- Print compatible with Python3
- Add travis
- Update README and change to README.md

### CODE REVIEW

**Comment by Rayman** [comment]
I don't think its useful to convert tabs to spaces here because it's old code and you lose your `git blame`. What do you guys think?

**Comment by reinzor** [comment]
What was the issue here?

**Comment by reinzor** [comment]
I also don't get it why we have this package, why not just use http://wiki.ros.org/teleop_twist_keyboard

**Comment by MatthijsBurgh** [comment]
I was bored and I was scrolling through the issues. One issue was about not using the general teleop_twist_keyboard. I found that the only difference is the keybindings. We use the numpad instead of:
```
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
anything else : stop
```
I prefer our keybindings, so I suggest to keep our teleop keyboard.

Changes
I synced with the changes done in the teleop_twist_keyboard, fixed the exception handling, updated readme and added travis.

**Comment by LoyVanBeek** [comment]
Less code is often better code, so if we can use the regular (even if it uses different keys), I'd say use that. How often do we even use the keyboard for teleop with the new UI?

Ideally, the keybindings are parameters but that's not worth the effort.

**Pull request closed without merging**
